apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFDTVJMcGFkVXBZQlJBQW5iRWZ6Wi9zYldHVzJwR0pHUWxXbGc9PQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-kube
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFEOVV4QmJmWE9SQ3hBQTE2T1dNTlpWTjRuZDBlK08rTW1hSnc9PQo=